<?php
/**
 * Features custom post type and fields
 *
 * @package uri-modern-news
 */

if ( function_exists( 'acf_add_local_field_group' ) ) :

acf_add_local_field_group(
	array(
		'key' => 'group_5c23a496d6004',
		'title' => 'COPE Fields',
		'fields' => array(
			array(
				'key' => 'field_5911c478a8175',
				'label' => 'Short Headline',
				'name' => 'short_headline',
				'type' => 'text',
				'instructions' => 'A short version of the headline (5 words or less).	Written and optimized for the web.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5734b7fc07aed',
				'label' => 'Deck',
				'name' => 'deck',
				'type' => 'textarea',
				'instructions' => 'A short summary (sentence) that explains what the article is about. Limit 250 characters.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5734b86f07aee',
				'label' => 'Lead',
				'name' => 'lead',
				'type' => 'textarea',
				'instructions' => 'The first paragraph of the story.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5734b8bd07aef',
				'label' => 'Nutshell',
				'name' => 'nutshell',
				'type' => 'textarea',
				'instructions' => 'A brief description of the key points.	Who, what, when, where, why, and how. Can be bullet points.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5911c4f3143ac',
				'label' => 'Square Image',
				'name' => 'image_square',
				'type' => 'image',
				'instructions' => 'A square-cropped version of the featured image for use on the homepage, News from URI, and other publications.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'return_format' => 'array',
				'min_width' => 0,
				'min_height' => 0,
				'min_size' => 0,
				'max_width' => 0,
				'max_height' => 0,
				'max_size' => 0,
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
				array(
					'param' => 'post_category',
					'operator' => '==',
					'value' => '2',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(),
		'active' => 1,
		'description' => '',
	)
	);

acf_add_local_field_group(
	array(
		'key' => 'group_5c23a496dfd24',
		'title' => 'Experts',
		'fields' => array(
			array(
				'key' => 'field_5716706d612bd',
				'label' => 'Sort Name',
				'name' => 'sort_name',
				'type' => 'text',
				'instructions' => 'The name that should be used when sorting experts alphabetically.	Usually, the surname of the expert.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 60,
			),
			array(
				'key' => 'field_5716709d612be',
				'label' => 'Position',
				'name' => 'position',
				'type' => 'text',
				'instructions' => 'An expert\'s job title or position at the university.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 255,
			),
			array(
				'key' => 'field_5716717eb871f',
				'label' => 'Telephone',
				'name' => 'telephone',
				'type' => 'text',
				'instructions' => 'Enter a single phone number.	Use periods as separators.	e.g. 401.874.1000',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 20,
			),
			array(
				'key' => 'field_57167160b871e',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'text',
				'instructions' => 'The email address for this expert.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 60,
			),
			array(
				'key' => 'field_571670ddd116b',
				'label' => 'Links',
				'name' => 'links',
				'type' => 'textarea',
				'instructions' => 'Use HTML to markup links for this expert.	e.g. &lt;a href="URL"&gt;LINK TEXT&lt;/a&gt;',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '<a href="URL">LINK TEXT</a>',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'br',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_category',
					'operator' => '==',
					'value' => '7',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(),
		'active' => 1,
		'description' => '',
	)
	);

acf_add_local_field_group(
	array(
		'key' => 'group_5c23a496e7db4',
		'title' => 'For Journalists',
		'fields' => array(
			array(
				'key' => 'field_5734a24510e13',
				'label' => 'Show the Media Box',
				'name' => 'show_the_media_box',
				'type' => 'checkbox',
				'instructions' => 'Select this option to show the Media (For Journalists) box on the news story page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Show' => 'Show the Media Box',
				),
				'default_value' => array(),
				'layout' => 'vertical',
				'allow_custom' => 0,
				'save_custom' => 0,
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5744d87793168',
				'label' => 'Attachment',
				'name' => 'attachment',
				'type' => 'file',
				'instructions' => 'Attach a file for journalists here.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5734a24510e13',
							'operator' => '==',
							'value' => 'Show',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'library' => 'uploadedTo',
				'return_format' => 'array',
				'min_size' => 0,
				'max_size' => 0,
				'mime_types' => '',
			),
			array(
				'key' => 'field_5744d9d1879df',
				'label' => 'More Text',
				'name' => 'more_text',
				'type' => 'wysiwyg',
				'instructions' => 'Add custom links to the "More" box at the bottom of the story.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '<br />
<a href="https://securelb.imodules.com/s/1638/03-Foundation/interior-hybrid.aspx?sid=1638&gid=3&pgid=770&cid=2270&utm_source=news&utm_medium=more&utm_campaign=giving">Support the University of Rhode Island</a>.',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'tabs' => 'all',
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_category',
					'operator' => '==',
					'value' => '2',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(),
		'active' => 1,
		'description' => '',
	)
	);

acf_add_local_field_group(
	array(
		'key' => 'group_5c23a496ed67d',
		'title' => 'Media',
		'fields' => array(
			array(
				'key' => 'field_5734a0330be6f',
				'label' => 'Embed Code',
				'name' => 'embed_code',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(),
		'active' => 1,
		'description' => '',
	)
	);

acf_add_local_field_group(
	array(
		'key' => 'group_5c23a496f02fd',
		'title' => 'Media Contact Fields',
		'fields' => array(
			array(
				'key' => 'field_56f97eaba1a90',
				'label' => 'First Name',
				'name' => 'first_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array(
				'key' => 'field_56f97ed1a1a91',
				'label' => 'Last Name',
				'name' => 'last_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array(
				'key' => 'field_56f97edca1a92',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array(
				'key' => 'field_56f97eeca1a93',
				'label' => 'Telephone',
				'name' => 'telephone',
				'type' => 'text',
				'instructions' => 'e.g. 401-874-1234',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_category',
					'operator' => '==',
					'value' => '3',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(),
		'active' => 1,
		'description' => '',
	)
	);

acf_add_local_field_group(
	array(
		'key' => 'group_5c23a49702a08',
		'title' => 'Press Release Fields',
		'fields' => array(
			array(
				'key' => 'field_56fa7fca33192',
				'label' => 'Legacy Serial Number',
				'name' => 'legacy_serial_number',
				'type' => 'number',
				'instructions' => 'Ignore this field.	It\'s a temporary bridge between the new site and the old, and it\'s irrelevant to humans.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 999999,
				'step' => '',
			),
			array(
				'key' => 'field_56fa801133193',
				'label' => 'Media Contact',
				'name' => 'media_contact',
				'type' => 'relationship',
				'instructions' => 'Select the media contact for this release.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'post_type' => array(
					0 => 'post',
				),
				'taxonomy' => array(
					0 => 'category:3',
				),
				'filters' => array(
					0 => 'search',
				),
				'max' => '',
				'min' => 0,
				'elements' => array(
					0 => 'post_type',
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_category',
					'operator' => '==',
					'value' => '2',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(),
		'active' => 1,
		'description' => '',
	)
	);

acf_add_local_field_group(
	array(
		'key' => 'group_5c23a49706ec8',
		'title' => 'RAMFAM',
		'fields' => array(
			array(
				'key' => 'field_5716caf2f5eec',
				'label' => 'URL',
				'name' => 'url',
				'type' => 'text',
				'instructions' => 'The URL that the image will link to.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'http://www.gorhody.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_category',
					'operator' => '==',
					'value' => '356',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(),
		'active' => 1,
		'description' => '',
	)
	);

acf_add_local_field_group(
	array(
		'key' => 'group_5c23a497098a0',
		'title' => 'URI in the News',
		'fields' => array(
			array(
				'key' => 'field_5744b0fd7993d',
				'label' => 'Publication Name',
				'name' => 'publication_name',
				'type' => 'text',
				'instructions' => 'The name of the publication that covered URI.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5744b11f7993e',
				'label' => 'URL',
				'name' => 'url',
				'type' => 'text',
				'instructions' => 'The URL of the coverage.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5744b17179940',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'F j, Y',
				'first_day' => 0,
				'return_format' => 'd/m/Y',
				'save_format' => 'yymmdd',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_category',
					'operator' => '==',
					'value' => '366',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(),
		'active' => 1,
		'description' => '',
	)
	);

endif;
